package com.mol.anurag.mol_backend.game.event;

import java.util.List;
import java.util.UUID;

public record BallResolvedEvent(
        String eventType,
        UUID matchId,
        UUID duelId,
        Integer batsmanPick,
        Integer bowlerPick,
        boolean wicket,
        boolean batsmanMissed,
        boolean bowlerMissed,
        int runsOnBall,
        int duelScoreA,
        int duelScoreB,
        UUID battingPlayerId,
        UUID bowlingPlayerId,
        int ballsRemaining,
        int teamAScore,
        int teamBScore,
        int teamAWickets,
        int teamBWickets,
        List<String> teamABallMarks,
        List<String> teamBBallMarks,
        String duelStatus,
        boolean playerAOut,
        boolean playerBOut) {

    public static BallResolvedEvent of(
            UUID matchId,
            UUID duelId,
            Integer batsmanPick,
            Integer bowlerPick,
            boolean wicket,
            boolean batsmanMissed,
            boolean bowlerMissed,
            int runsOnBall,
            int duelScoreA,
            int duelScoreB,
            UUID battingPlayerId,
            UUID bowlingPlayerId,
            int ballsRemaining,
            int teamAScore,
            int teamBScore,
            int teamAWickets,
            int teamBWickets,
            List<String> teamABallMarks,
            List<String> teamBBallMarks,
            String duelStatus,
            boolean playerAOut,
            boolean playerBOut) {
        return new BallResolvedEvent(
                "BALL_RESOLVED",
                matchId,
                duelId,
                batsmanPick,
                bowlerPick,
                wicket,
                batsmanMissed,
                bowlerMissed,
                runsOnBall,
                duelScoreA,
                duelScoreB,
                battingPlayerId,
                bowlingPlayerId,
                ballsRemaining,
                teamAScore,
                teamBScore,
                teamAWickets,
                teamBWickets,
                teamABallMarks,
                teamBBallMarks,
                duelStatus,
                playerAOut,
                playerBOut);
    }
}
