apiVersion: v1
kind: ConfigMap
metadata:
  name: mol-backend-config
  namespace: mol
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_DATA_REDIS_PORT: '6379'
  MOL_CORS_ALLOWED_ORIGINS: http://localhost:3000
  # SPRING_DATASOURCE_URL set per environment — use external managed PostgreSQL
